# Generated by Django 4.0.6 on 2022-08-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_attribute_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='att_name',
        ),
    ]
